\merlin\nucleo\objeto.cls
\merlin\nucleo\classe.cls
\merlin\nucleo\tarefa.cls
\merlin\nucleo\video.cls
\merlin\nucleo\memoria.cls
\merlin\nucleo\simbolo.cls
\merlin\nucleo\retang.cls
\merlin\nucleo\quadro.cls
\merlin\nucleo\regiao.cls
\merlin\nucleo\portas.cls
\merlin\nucleo\mensagem.cls
\merlin\nucleo\sincrona.cls
\merlin\nucleo\sinaliza.cls
\merlin\nucleo\tela.cls
\merlin\nucleo\teclado.cls
\merlin\nucleo\janela.cls
\merlin\administ\dummy.mrl 500 0
\merlin\administ\usuario1.mrl 101 0
\merlin\administ\usuario2.mrl 102 0
\merlin\administ\usuario3.mrl 103 0
\merlin\administ\usuario4.mrl 104 0
\merlin\administ\usuario5.mrl 105 0
\merlin\administ\admscren.mrl 10 0
\merlin\administ\admtaref.mrl 10 0
