#define _classe           0
#define _superClasse      2
#define _metInstancia     4
#define _metClasse        8
#define _numMetInstancia 12
#define	_numMetClasse    14
#define _primSimbolo     16

#define _nome             2
#define _estado           4
#define _priFixa          6
#define _priAtual         8
#define _proxTarefa      10
#define _filaMensagens   12
#define _tarefaAnterior  14
#define _tarefaSeguinte  16
#define _tss             18
#define _blink           20
#define _selTarefa       64
#define _numTarefa       66

#define _esqprox          2
#define _dirprox          4
#define _xorigem          6
#define _yorigem          8
#define _comprimento     10
#define _altura          12
#define _fundo           14
#define _regiaoVisivel   16
#define _celulaLivre      9
#define _primCelula      10

#define _proxMSG          2
#define _remetente        4
#define _nParametros      6
#define _objetoRec        8
#define _seletorMSG      10
#define _buffer          12

#define LIMITE       0xffff